// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"encoding/json"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	recover2 "github.com/gofiber/fiber/v2/middleware/recover"
	"product/internal/cache"
	"product/internal/config"
	"product/internal/db"
	"product/internal/handler"
	"product/internal/middleware"
	"product/internal/repository"
	"product/internal/router"
	"product/internal/service"
	"time"
)

// Injectors from server.go:

func New() (*fiber.App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	configDB := config.NewDBConfig(configConfig)
	gormDB, err := db.Connect(configDB)
	if err != nil {
		return nil, err
	}
	redis := config.NewRedisConfig(configConfig)
	client, err := cache.NewRedisClient(redis)
	if err != nil {
		return nil, err
	}
	productRepository := repository.NewProductRepository(gormDB, client)
	productService := service.NewProductService(productRepository)
	productHandler := handler.NewProductHandler(productService)
	routerHandler := router.NewRouterHandler(productHandler)
	middlewareMiddleware := middleware.NewMiddleware(client)
	app := NewServer(routerHandler, middlewareMiddleware)
	return app, nil
}

// server.go:

func NewServer(router2 *router.RouterHandler, md *middleware.Middleware) *fiber.App {
	app := fiber.New(fiber.Config{
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 5 * time.Second,
		JSONDecoder:  json.Unmarshal,
		JSONEncoder:  json.Marshal,
	})

	app.Use(logger.New())

	recoveryConfig := recover2.ConfigDefault
	app.Use(recover2.New(recoveryConfig))
	router2.
		InitRouter(app, md)

	return app
}
