// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc

import (
	"product/internal/cache"
	"product/internal/config"
	"product/internal/db"
	"product/internal/grpc/service"
	"product/internal/repository"
	service2 "product/internal/service"
)

// Injectors from wire_grpc.go:

func InitGRPCServer() (*service.ProductService, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	configDB := config.NewDBConfig(configConfig)
	gormDB, err := db.Connect(configDB)
	if err != nil {
		return nil, err
	}
	redis := config.NewRedisConfig(configConfig)
	client, err := cache.NewRedisClient(redis)
	if err != nil {
		return nil, err
	}
	productRepository := repository.NewProductRepository(gormDB, client)
	productService := service2.NewProductService(productRepository)
	serviceProductService := service.NewProductService(productService)
	return serviceProductService, nil
}
