// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"category/internal/cache"
	"category/internal/config"
	"category/internal/db"
	"category/internal/grpc/client"
	"category/internal/grpc/provider"
	"category/internal/handler"
	"category/internal/middleware"
	"category/internal/repository"
	"category/internal/router"
	"category/internal/service"
	"encoding/json"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	recover2 "github.com/gofiber/fiber/v2/middleware/recover"
	"time"
)

// Injectors from server.go:

func New() (*fiber.App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	configDB := config.NewDBConfig(configConfig)
	gormDB, err := db.Connect(configDB)
	if err != nil {
		return nil, nil, err
	}
	redis := config.NewRedisConfig(configConfig)
	redisClient, err := cache.NewRedisClient(redis)
	if err != nil {
		return nil, nil, err
	}
	categoryRepository := repository.NewCategoryRepository(gormDB, redisClient)
	clientConn, cleanup, err := provider.ProvideGRPCConnection(configConfig)
	if err != nil {
		return nil, nil, err
	}
	productClient := client.NewProductClient(clientConn)
	categoryService := service.NewCategoryService(categoryRepository, productClient)
	categoryHandler := handler.NewCategoryHandler(categoryService)
	routerHandler := router.NewRouterHandler(categoryHandler)
	middlewareMiddleware := middleware.NewMiddleware(redisClient)
	app := NewServer(routerHandler, middlewareMiddleware)
	return app, func() {
		cleanup()
	}, nil
}

// server.go:

func NewServer(router2 *router.RouterHandler, md *middleware.Middleware) *fiber.App {
	app := fiber.New(fiber.Config{
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 5 * time.Second,
		JSONDecoder:  json.Unmarshal,
		JSONEncoder:  json.Marshal,
	})

	app.Use(logger.New())

	recoveryConfig := recover2.ConfigDefault
	app.Use(recover2.New(recoveryConfig))
	router2.
		InitRouter(app, md)

	return app
}
